events { worker_connections 1024; }

http {
    server {
        listen 80;

        location /api/products {
            proxy_pass http://product-service:3001;
        }

        location /api/orders {
            proxy_pass http://order-service:3002;
        }

        location /api/kitchen {
            proxy_pass http://kitchen-service:3003;
        }

        location /api/notifications {
            proxy_pass http://notification-service:3004;
        }
    }
}