events { worker_connections 1024; }

http {
    server {
        listen 80;

        location /api/products {
            proxy_pass http://product-service:3001;
        }

        location /api/orders {
            proxy_pass http://order-service:3002;
        }
    }
}